name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check for breaking changes
      run: |
        echo "Checking for breaking changes..."
        # Check if critical files were modified
        if git diff --name-only origin/main | grep -E "(v6/pine-constants-complete|v6/pine-builtins-complete|accurateValidator)"; then
          echo "⚠️  Critical validation files modified - ensure tests pass"
        fi

    - name: Run full test suite
      run: npm test

    - name: Run self-test
      run: node test/v0.4.0-self-test.js

    - name: Build check
      run: npm run build

    - name: Comment PR with test results
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const fs = require('fs');
          const testsPassed = ${{ job.status == 'success' }};

          const comment = testsPassed
            ? '✅ All checks passed! Ready for review.'
            : '❌ Some checks failed. Please review the workflow logs.';

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
